<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Owner-PC" ignored="0" name="BankingApp Test(failed)" tests="4" failures="3" timestamp="2021-05-07T10:20:07 IST" time="162.406" errors="0">
  <testcase name="loginTest" time="5.969" classname="com.IntBanking.TestCases.TC_LoginTest_01"/>
  <testcase name="loginDDT" time="49.469" classname="com.IntBanking.TestCases.TC_LoginDDT_02">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.IntBanking.TestCases.TC_LoginDDT_02.loginDDT(TC_LoginDDT_02.java:32)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="78.255" classname="com.IntBanking.TestCases.TC_LoginDDT_02">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.IntBanking.TestCases.TC_LoginDDT_02.loginDDT(TC_LoginDDT_02.java:32)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="6.621" classname="com.IntBanking.TestCases.TC_LoginDDT_02">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.IntBanking.TestCases.TC_LoginDDT_02.loginDDT(TC_LoginDDT_02.java:32)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
</testsuite> <!-- BankingApp Test(failed) -->
